career-stats-settings:
    data:
        initialVisited: true
        welcomedSeason: 12
    schemaVersion: 1
champ-select:
    data:
        skins:
            10: 10000
            106: 106000
            11: 11000
            121: 121000
            127: 127000
            133: 133000
            15: 15000
            157: 157000
            161: 161000
            17: 17000
            18: 18000
            2: 2000
            20: 20000
            202: 202000
            21: 21000
            22: 22000
            222: 222000
            223: 223000
            267: 267000
            268: 268000
            27: 27000
            28: 28000
            29: 29001
            30: 30000
            34: 34000
            350: 350000
            360: 360000
            40: 40000
            41: 41000
            420: 420000
            432: 432000
            498: 498000
            50: 50000
            55: 55000
            60: 60000
            63: 63000
            67: 67000
            68: 68000
            69: 69000
            72: 72000
            75: 75000
            77: 77000
            8: 8000
            84: 84000
            876: 876000
            92: 92000
            96: 96000
        spells:
            1020:
            - 6
            - 4
            400:
            - 3
            - 4
            420:
            - 7
            - 21
            450:
            - 1
            - 4
            700:
            - 14
            - 4
            830:
            - 7
            - 21
            850:
            - 11
            - 4
    schemaVersion: 1
clash-tutorial:
    data:
        captainInviteStep: true
        captainLockinStep: true
        captainRewardStep: true
        captainRoleStep: true
        captainTicketStep: true
        initialized: true
        memberJoinTeamStep: true
        memberLockinStep: true
        memberRewardStep: true
        memberRoleStep: true
        memberTicketStep: true
        rosterDetailsModalLogoStep: true
        rosterDetailsModalNameTagStep: true
        smsButtonStep: true
        version: 1
    schemaVersion: 1
cosmetics-last-viewed-date:
    data:
        typeToLastOpenedDate:
            COMPANION: 1649275996
            TFT_DAMAGE_SKIN: 1649275825
            TFT_MAP_SKIN: 1649275825
    schemaVersion: 1
cosmetics-settings:
    data:
        companions:
            hideUnowned: true
    schemaVersion: 1
custom-spell-selections:
    data:
        custom-spell-selections:
            spell1: 7
            spell2: 4
    schemaVersion: 0
emotes:
    data:
        newEmotes:
        - 1513
    schemaVersion: 1
lol-challenges-latest-level-up:
    data:
        lastLevelUpTime: 1664403753065
    schemaVersion: 1
lol-champ-select:
    data:
        reportAndMutingTooltipShown: true
    schemaVersion: 0
lol-clash:
    data:
        clash-start-modal-seen: true
        lftPlayerToggleTooltipSeen: true
        openTeamToggleTooltipSeen: true
    schemaVersion: 1
lol-collection-champions:
    data:
        groupingDropdownKey: ""
        lastVisitTime: 1664425117210
        sortingDropdownKey: ""
        unownedFilter: "none"
    schemaVersion: 1
lol-collection-summoner-icons:
    data:
        groupingDropdownKey: "myCollection"
        lastVisitTime: 1663826098566
        sortingDropdownKey: "acquisitionDate"
        unavailableFilter: false
        unownedFilter: false
    schemaVersion: 2
lol-collection-wards:
    data:
        groupingDropdownKey: "myCollection"
        lastVisitTime: 1649275965799
        sortingDropdownKey: "acquisitionDate"
        unavailableFilter: false
        unownedFilter: false
    schemaVersion: 3
lol-customizer-icons:
    data:
        lastVisitTime: 1663880458029
    schemaVersion: 1
lol-customizer-titles:
    data:
        lastVisitTime: 1663880462160
    schemaVersion: 1
lol-customizer-tokens:
    data:
        lastVisitTime: 1663880479209
    schemaVersion: 1
lol-general:
    data:
        uploadCrashReports: true
    schemaVersion: 0
lol-home-hubs:
    data:
        anima-squad-hub-2022:
            watchedIntro: true
        sentinels-hub-2021:
            clickedSkip: true
            skipAll: true
            watchedIntro: true
    schemaVersion: 1
lol-honor:
    data:
        recallReleaseNotified: true
    schemaVersion: 1
lol-leagues:
    data:
        hasSeenFlexRestrictionModal: true
        last-split-end-notification: 12.100000
        last-split-start-modal: 12.100000
    schemaVersion: 1
lol-loot:
    data:
        mythicEssenceModalSeen: true
        mythicEssenceNavigationTooltipSeen: true
    schemaVersion: 1
lol-notifications:
    data:
        rgmNotificationTimestamp: 1663324064775
    schemaVersion: 1
lol-npe-first-touch:
    data: null
    schemaVersion: 1
lol-npe-rewards:
    data:
        challenges:
            allMissionsCompleted: false
            totalCount: 8
        login:
            allRewardsClaimed: false
            lastCompletedMissionDate: 1641615940000
            lastCompletedMissionInternalName: "npe_rewards_login_v1_step4"
    schemaVersion: 1
lol-npe-tutorial-path:
    data:
        hasSeenTutorialPath: true
        hasSkippedTutorialPath: false
        shouldSeeNewPlayerExperience: false
    schemaVersion: 1
lol-parties:
    data:
        hasSeenOpenPartyFirstExperience: true
        hasSeenOpenPartyTooltip: true
    schemaVersion: 1
lol-player-behavior:
    data:
        codeOfConductAccepted: true
    schemaVersion: 0
lol-premade-voice:
    data:
        autoJoin: true
        inputMode: "voiceActivity"
        muteOnConnect: false
        pushToTalkKey: "[<Unbound>]"
        showFirstExperienceInGame: true
        showFirstExperienceInLCU: false
    schemaVersion: 1
lol-profiles:
    data:
        ranked-reference-modal-login-seen-for-season: 12
    schemaVersion: 0
lol-skins-viewer:
    data:
        groupingDropdownKey: "myCollection"
        lastVisitTime: 1649130876033
        sortingDropdownKey: "acquisitionDate"
        unownedFilter: false
    schemaVersion: 2
lol-tft:
    data:
        lastTftGameQueueId: 1090
        previouslySeenSeasons: "TFT6_Series,TFT6_Act2_Series,TFT7_5_Series"
        seenOfferIds:
            storeOfferIds:
            - "f34ed470-015d-428f-b290-c1a285636ec4"
            - "484c2f9c-21db-4e03-8f22-acf6cbca1648"
            tacticianOfferIds:
            - "2bc19a3c-4c70-4d82-9881-4f958113f39a"
    schemaVersion: 1
lol-tutorial:
    data:
        Map22_TFT_TutorialSeen: true
        championSelectRunesTooltipSeenCount: 9
        perksCreateNewPageSeen: true
        perksPresetPagesSeen: true
    schemaVersion: 1
