champ-select:
    data:
        skins:
            101: 101000
            11: 11000
            134: 134000
            136: 136000
            14: 14000
            142: 142000
            150: 150000
            17: 17000
            18: 18000
            21: 21000
            222: 222000
            30: 30000
            4: 4000
            61: 61000
            69: 69000
            78: 78000
            81: 81000
            86: 86000
        spells:
            830:
            - 4
            - 7
    schemaVersion: 1
lol-champ-select:
    data:
        reportAndMutingTooltipShown: true
    schemaVersion: 0
lol-collection-champions:
    data:
        groupingDropdownKey: "allChampions"
        lastVisitTime: 1663975800414
        sortingDropdownKey: "firstLetterAscending"
        unownedFilter: "none"
    schemaVersion: 1
lol-general:
    data:
        uploadCrashReports: true
    schemaVersion: 0
lol-honor:
    data:
        recallReleaseNotified: true
    schemaVersion: 1
lol-notifications:
    data:
        rgmNotificationTimestamp: 1662616555679
    schemaVersion: 1
lol-npe-rewards:
    data:
        challenges:
            allMissionsCompleted: false
            totalCount: 8
        login:
            allRewardsClaimed: false
            lastCompletedMissionDate: 1662963202000
            lastCompletedMissionInternalName: "npe_rewards_login_v1_step6"
    schemaVersion: 1
lol-npe-tutorial-path:
    data:
        hasSeenTutorialPath: false
        hasSkippedTutorialPath: false
        shouldSeeNewPlayerExperience: false
    schemaVersion: 1
lol-parties:
    data:
        hasSeenOpenPartyFirstExperience: true
        hasSeenOpenPartyTooltip: true
    schemaVersion: 1
lol-player-behavior:
    data:
        codeOfConductAccepted: true
    schemaVersion: 0
lol-premade-voice:
    data:
        autoJoin: true
        inputMode: "voiceActivity"
        muteOnConnect: false
        pushToTalkKey: "[<Unbound>]"
        showFirstExperienceInGame: true
        showFirstExperienceInLCU: true
    schemaVersion: 1
lol-profiles:
    data:
        ranked-reference-modal-login-seen-for-season: 12
    schemaVersion: 0
lol-tft:
    data:
        previouslySeenSeasons: "TFT7_5_Series"
    schemaVersion: 1
lol-tutorial:
    data:
        championSelectRunesTooltipSeenCount: 5
    schemaVersion: 1
