career-stats-settings:
    data:
        initialVisited: true
        welcomedSeason: 12
    schemaVersion: 1
champ-select:
    data:
        skins:
            10: 10000
            117: 117000
            119: 119000
            126: 126000
            15: 15000
            150: 150000
            16: 16000
            161: 161000
            17: 17000
            202: 202000
            22: 22000
            234: 234000
            266: 266000
            267: 267000
            27: 27000
            34: 34000
            350: 350000
            37: 37000
            40: 40000
            42: 42000
            429: 429000
            44: 44000
            498: 498000
            516: 516000
            54: 54000
            63: 63000
            67: 67000
            7: 7000
            75: 75000
            78: 78000
            90: 90000
            96: 96000
            99: 99000
        spells:
            400:
            - 14
            - 4
            420:
            - 14
            - 7
            430:
            - 21
            - 4
            450:
            - 21
            - 4
            700:
            - 4
            - 14
            830:
            - 7
            - 21
    schemaVersion: 1
clash-tutorial:
    data:
        captainInviteStep: true
        captainLockinStep: true
        captainRewardStep: true
        captainRoleStep: true
        captainTicketStep: true
        initialized: true
        memberJoinTeamStep: true
        memberLockinStep: true
        memberRewardStep: true
        memberRoleStep: true
        memberTicketStep: true
        rosterDetailsModalLogoStep: true
        rosterDetailsModalNameTagStep: true
        smsButtonStep: true
        version: 2
    schemaVersion: 1
custom-spell-selections:
    data:
        custom-spell-selections:
            spell1: 1
            spell2: 4
    schemaVersion: 0
emotes:
    data:
        newEmotes:
        - 3246
        - 3897
        - 3896
        - 1516
        - 3000
        - 3166
    schemaVersion: 1
lol-challenges:
    data:
        introCollectionModalShown: true
        introModalShown: true
    schemaVersion: 1
lol-champ-select:
    data:
        reportAndMutingTooltipShown: true
    schemaVersion: 0
lol-clash:
    data:
        lftPlayerToggleTooltipSeen: true
        openTeamToggleTooltipSeen: true
    schemaVersion: 0
lol-collection-champions:
    data:
        groupingDropdownKey: ""
        lastVisitTime: 1664155672397
        sortingDropdownKey: ""
        unownedFilter: "none"
    schemaVersion: 1
lol-collection-summoner-icons:
    data:
        groupingDropdownKey: "myCollection"
        lastVisitTime: 1664151397726
        sortingDropdownKey: "acquisitionDate"
        unavailableFilter: false
        unownedFilter: false
    schemaVersion: 2
lol-general:
    data:
        uploadCrashReports: true
    schemaVersion: 0
lol-home-hubs:
    data:
        anima-squad-hub-2022:
            watchedIntro: true
        lunar-revel-hub-2022:
            currentTheme: "fire"
        star-guardians-metagame-hub-2022:
            0: "[]"
            1: "0"
            2: "0"
            ambientAudioDisabled: "false"
            fallbackSaved: "true"
            fellback: "false"
            introWatched: "true"
            motionDisabled: "false"
            tutorialWatched: "false"
    schemaVersion: 1
lol-honor:
    data:
        recallReleaseNotified: true
    schemaVersion: 1
lol-leagues:
    data:
        hasSeenFlexRestrictionModal: true
        last-split-end-notification: 12.200000
        last-split-start-modal: 12.300000
    schemaVersion: 1
lol-loot:
    data:
        mythicEssenceModalSeen: true
        mythicEssenceNavigationTooltipSeen: true
    schemaVersion: 1
lol-notifications:
    data:
        disableCollectionsNotifications: true
        disableEsportsNotifications: true
        rgmNotificationTimestamp: 1663323001445
    schemaVersion: 1
lol-npe-first-touch:
    data:
        modeSelected: "summoners-rift"
    schemaVersion: 1
lol-npe-rewards:
    data:
        challenges:
            allMissionsCompleted: false
            totalCount: 8
        login:
            allRewardsClaimed: false
            lastCompletedMissionDate: 1634405127000
            lastCompletedMissionInternalName: "npe_rewards_login_v1_step2"
    schemaVersion: 1
lol-npe-tutorial-path:
    data:
        hasSeenTutorialPath: true
        hasSkippedTutorialPath: true
        shouldSeeNewPlayerExperience: true
    schemaVersion: 1
lol-parties:
    data:
        hasSeenOpenPartyFirstExperience: true
        hasSeenOpenPartyTooltip: true
    schemaVersion: 1
lol-player-behavior:
    data:
        codeOfConductAccepted: true
    schemaVersion: 0
lol-premade-voice:
    data:
        autoJoin: false
        inputMode: "voiceActivity"
        muteOnConnect: false
        pushToTalkKey: "[<Unbound>]"
        showFirstExperienceInGame: false
        showFirstExperienceInLCU: false
    schemaVersion: 1
lol-profiles:
    data:
        ranked-reference-modal-login-seen-for-season: 12
    schemaVersion: 0
lol-skins-viewer:
    data:
        groupingDropdownKey: "myCollection"
        lastVisitTime: 1657497049878
        sortingDropdownKey: "acquisitionDate"
        unownedFilter: false
    schemaVersion: 2
lol-tft:
    data:
        lastTftGameQueueId: 1090
        previouslySeenSeasons: "TFT5_5_Series,TFT6_Series,TFT6_Act2_Series,TFT7_Series,TFT7_5_Series"
        seenOfferIds:
            storeOfferIds:
            - "3dd06259-0805-40a5-87b7-c66ff8aaf14c"
            - "10d94ace-65bb-427e-bc9a-363b21c29b08"
            tacticianOfferIds:
            - "b3b16b94-9542-430d-8720-b574b683d5d5"
    schemaVersion: 1
lol-tutorial:
    data:
        championSelectRunesTooltipSeenCount: 9
        npeRewardsV1IntroSeen: true
        perksCreateNewPageSeen: true
        perksPresetPagesSeen: true
        perksPrimaryPathSeen: true
        perksStatModsSeen: true
    schemaVersion: 1
personalized-offers:
    data:
        lastViewedTimestamp: "2022-05-16T01:04:44.565Z"
    schemaVersion: 1
