page-settings:
    data:
        pages: []
        perShardPerkBooks:
            na1:
                currentPageId: 2089277305
                pages:
                -   autoModifiedSelections: []
                    current: true
                    id: 2089277305
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isValid: true
                    lastModified: 1664737215606
                    name: "New Runes Page 1"
                    order: 0
                    primaryStyleId: 8200
                    selectedPerkIds:
                    - 8214
                    - 8275
                    - 8233
                    - 8237
                    - 9111
                    - 8299
                    - 5007
                    - 5008
                    - 5001
                    subStyleId: 8000
                -   autoModifiedSelections: []
                    current: false
                    id: 1261858073
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isValid: false
                    lastModified: 1648693228647
                    name: "New Runes Page 2"
                    order: 1
                    primaryStyleId: 8300
                    selectedPerkIds:
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    subStyleId: -1
                -   autoModifiedSelections: []
                    current: false
                    id: 148143295
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isValid: true
                    lastModified: 1649101847304
                    name: "New Runes Page 3"
                    order: 2
                    primaryStyleId: 8000
                    selectedPerkIds:
                    - 8008
                    - 9111
                    - 9104
                    - 8014
                    - 8139
                    - 8135
                    - 5005
                    - 5008
                    - 5002
                    subStyleId: 8100
        settings:
            gameplayPatchVersionSeen: "11.23"
            gameplayUpdatedPerksSeen: []
            gridModeEnabled: true
            showLongDescriptions: true
            showPresetPages: false
    schemaVersion: 5
