page-settings:
    data:
        pages: []
        perShardPerkBooks:
            na1:
                currentPageId: 1446948543
                pages:
                -   autoModifiedSelections: []
                    current: true
                    id: 1446948543
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isValid: true
                    lastModified: 1664160207701
                    name: "New Runes Page 1"
                    order: 0
                    primaryStyleId: 8200
                    selectedPerkIds:
                    - 8214
                    - 8275
                    - 8210
                    - 8236
                    - 8009
                    - 8299
                    - 5008
                    - 5008
                    - 5002
                    subStyleId: 8000
                -   autoModifiedSelections: []
                    current: false
                    id: 1983644456
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isValid: false
                    lastModified: 1664157382440
                    name: "New Runes Page 2"
                    order: 1
                    primaryStyleId: 8000
                    selectedPerkIds:
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    subStyleId: -1
                -   autoModifiedSelections: []
                    current: false
                    id: 1202625383
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isValid: false
                    lastModified: 1664157428386
                    name: "New Runes Page 3"
                    order: 2
                    primaryStyleId: 8200
                    selectedPerkIds:
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    subStyleId: -1
        settings:
            gameplayPatchVersionSeen: "11.23"
            gameplayUpdatedPerksSeen:
            - 8369
            gridModeEnabled: true
            showLongDescriptions: true
            showPresetPages: true
    schemaVersion: 5
