page-settings:
    data:
        pages: []
        perShardPerkBooks:
            na1:
                currentPageId: 958820755
                pages:
                -   autoModifiedSelections: []
                    current: true
                    id: 958820755
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isValid: true
                    lastModified: 1664757706072
                    name: "Blitz: Miss Fortune"
                    order: 0
                    primaryStyleId: 8200
                    selectedPerkIds:
                    - 8229
                    - 8226
                    - 8233
                    - 8236
                    - 8304
                    - 8345
                    - 5008
                    - 5008
                    - 5003
                    subStyleId: 8300
        settings:
            gameplayPatchVersionSeen: "11.23"
            gameplayUpdatedPerksSeen: []
            gridModeEnabled: false
            showLongDescriptions: false
            showPresetPages: true
    schemaVersion: 5
